# -*- mode: ruby -*-
# vi: set ft=ruby :

### 虚拟机环境配置
# 1. 定义虚拟机配置: box, cpus, mem, ip(private)
vms = {
  :web1 => ['centos/7', '2', '2048', '10.1.3.101'],
  :db1 => ['ubuntu/xenial64', '1', '1024', '10.1.3.111'],
  :db2 => ['centos/7', '1', '1024', '10.1.3.112'],
  :ftp1 => ['centos/7', '1', '1024', '10.1.3.121'],
}
# 2. 定义组名
group = "EBdev"
root_passwd = "kk"
packages_preinstalled = "vim"
# 3. 定义是否执行基本的provision
os_basic_setup = true
root_sshpasswordless = true
nodes_provision = true


### 默认配置
Vagrant.configure("2") do |config|

  config.vm.box_check_update = false

  config.vm.synced_folder "../common", "/common"

  config.vm.provider "virtualbox" do |vb|
  # vb.gui = true
  vb.customize ["modifyvm", :id, "--groups", "/#{group}"]

end

### 多节点配置
  vms.each do |m_name, m_config|
    config.vm.define "#{m_name}" do |m|

      m.vm.box = "#{m_config[0]}"
      m.vm.hostname = "#{m_name}"
      m.vm.network "private_network", ip: "#{m_config[3]}"

      m.vm.provider "virtualbox" do |vb|
        vb.name = "#{m_name}"
        vb.memory = "#{m_config[2]}"
        vb.cpus = "#{m_config[1]}"
      end


      if m.vm.box =~ /ubuntu\/[a-z]+64/
        linux_dist = "ubuntu"
	# ubuntu 无需安装 virtualbox guest extension
        m.vbguest.auto_update = false
      elsif m.vm.box =~ /centos\/[0-9]+/
        linux_dist = "centos"
      end

      # 进行操作系统基本配置：设置root密码，国内源等
      if os_basic_setup
        m.vm.provision "os", type: "shell" do |s|
          s.path = "../common/scripts/bootstrap-#{linux_dist}.sh"
          s.args = ["#{root_passwd}", "#{packages_preinstalled}"]
        end
      end

      # 配置root免密码登录
      if root_sshpasswordless
        m.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/my_id_rsa.pub"
        m.vm.provision "shell" do |s|
          s.path = "../common/scripts/ssh-passwordless.sh"
          s.args = [linux_dist]
        end
      end

      # 针对各个node进行不同的provision
      if nodes_provision
        m.vm.provision "nodes", type: "shell" do |s|
          s.path = "nodes-provision.sh"
          s.args = ["#{m_name}"]
        end
      end

      # 节点启动成功后给出消息
      if root_sshpasswordless
        config.vm.post_up_message = "#{m_name}启动成功，可使用SSH免密登录root[ssh root@#{m_config[3]}]。"
      elsif
        config.vm.post_up_message = "#{m_name}启动成功，可使用[vagrant ssh #{m_name}]访问。"
      end

    end
  end


end
