# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # 指定默认镜像box
  config.vm.box = "ubuntu/xenial64"

  # 检查box是否有更新，默认检查
  config.vm.box_check_update = false

  # 配置操作系统主机名（注：vagrant默认虚拟机为linux，可通过config.vm.guest配置）
  config.vm.hostname = "ubuntu"

  # Virtualbox相关的配置
  config.vm.provider "virtualbox" do |vb|
    # 启动虚拟机时是否打开virtualbox界面
    # vb.gui = true
    vb.cpus = 2
    vb.memory = "1024"
  end

  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/my_id_rsa.pub"
  config.vm.provision "shell", path: "~/.vagrant.d/scripts/bootstrap-ubuntu.sh"


  # 配置虚拟机启动完成后显示的信息
  config.vm.post_up_message = "启动成功，可使用root用户SSH免密登录。"

end
