# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.hostname = "devstack-mitaka"

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false

# config.vm.synced_folder "../common", "/common"

  config.vm.network "private_network", ip: "10.1.1.101"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "devstack-mitaka"
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "../common/bootstrap-ubuntu.sh"
  config.vm.provision "shell", path: "bootstrap.sh"

end
