# -*- mode: ruby -*-
# vi: set ft=ruby :

root_passwd = 'kk'

vms = {
  :mitaka => ['4', '8192', '10.1.1.101'],
  :newton => ['4', '8192', '10.1.1.102'],
  :ocata  => ['4', '8192', '10.1.1.103'],
}

Vagrant.configure("2") do |config|

  config.vm.box_check_update = false
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--groups", "/devstack"]
  end
  config.vm.provision "shell" do |s|
    s.path = "../common/bootstrap-ubuntu.sh"
    s.args = "#{root_passwd}"
  end

  vms.each do |m_name, m_config|
    config.vm.define "#{m_name}" do |m|
      m.vm.hostname = "devstack-#{m_name}"
      m.vm.network "private_network", ip: "#{m_config[2]}"
      m.vm.provider "virtualbox" do |vb|
        vb.name = "devstack-#{m_name}"
        vb.memory = "#{m_config[1]}"
        vb.cpus = "#{m_config[0]}"
      end
      m.vm.provision "shell" do |s|
        s.path = "bootstrap.sh"
	s.args = ["#{m_name}","#{m_config[2]}"]
      end
    end
  end
  
end
