# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.hostname = "devstack.kang.me"

  config.vm.box = "ubuntu/trusty64"

  config.vm.box_check_update = false

  config.vm.synced_folder "../common", "/common"

  config.vm.network "private_network", ip: "192.168.1.180"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "devstack"
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "../common/bootstrap.sh"
  config.vm.provision "shell", path: "bootstrap.sh"
# config.vm.provision "shell", path: "startup.sh", run: "always"

end
