# -*- mode: ruby -*-
# vi: set ft=ruby :

vms = {
  :node0 => ['2', '1536', '10.1.0.100'],
  :node1 => ['2', '1536', '10.1.0.101'],
  :node2 => ['2', '1536', '10.1.0.102'],
  :node3 => ['2', '1536', '10.1.0.103'],
}

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  # config.vm.box_url = "http://boxrepo.io/test.box"
  # config.vm.box_url = "file:///tmp/test.box"

  config.vm.box_check_update = false

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.cpus = 2
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--groups", "/testnodes"]
  end

### multinode

  # Loop creation
  vms.each do |m_name, m_config|
    config.vm.define "#{m_name}" do |m|

      m.vm.hostname = "#{m_name}"

      m.vm.network "private_network", ip: "#{m_config[2]}"

      m.vm.provider "virtualbox" do |vb|
        vb.name = "#{m_name}"
#        vb.memory = "#{m_config[1]}"
        vb.cpus = "#{m_config[0]}"
      end

      m.vm.provision "shell" do |s|
        s.inline = "echo \"Provisioning $1 with IP:$2\""
        s.args = ["#{m_name}","#{m_config[2]}"]
      end

    end
  end

end
