# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  # config.vm.box_url = "http://boxrepo.io/test.box"
  # config.vm.box_url = "file:///tmp/test.box"
  # config.vm.box_version >= 1.0,<1.5

  config.vm.box_check_update = false

  config.vm.hostname = "template"

  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "10.1.0.100"

  # config.vm.network "public_network", ip: "192.168.0.234"
  # config.vm.network "public_network", use_dhcp_assigned_default_route: true

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.name = "template"
    vb.cpus = 2
    vb.memory = "1024"
    vb.customize ["modifyvm", :id, "--groups", "/devstack"]
  end

  # config.vm.provision "hello", type: "shell", inline: "echo hello1", run: "always"

  # config.vm.provision "bootstrap", type: "shell" do |s|
  #   s.inline = "echo $1"
  #   s.args = ["hello, world!"]
  # end

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y git
  # SHELL

  # config.vm.post_up_message = "启动成功！"

end
