# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  config.vm.hostname = "devstack-ocata"

  config.vm.box = "ubuntu/xenial64"

  config.vm.box_check_update = false

# config.vm.synced_folder "../data", "/data"

  config.vm.network "private_network", ip: "10.1.1.103"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "devstack-ocata"
    vb.memory = "8192"
    vb.cpus = 4
  end

  config.vm.provision "shell", path: "bootstrap.sh"

end
