# -*- mode: ruby -*-
# vi: set ft=ruby :

### Configurations 
# [VM] name, cpus, memory(MB), ip(private), group name
# [OS] root-password, http(s)_proxy, packages to install
######################
group = "templates"
vms = {
  :centos7 => ['bento/centos-7', '1', '2048'],
  :centos8 => ['bento/centos-8', '1', '2048'],
  :ubuntu18 => ['bento/ubuntu-18.04', '1', '2048'],
  :ubuntu20 => ['bento/ubuntu-20.04', '1', '2048'],
}

# A new user you want to create besides "vagrant"
# If blank(""), the ssh-passwordless will be set on user "root"
new_user = "kang"

# Packages you want to install during provisioning
# If not blank(""), the installation process may cost more time
# packages_preinstalled = "vim curl wget tree"
packages_preinstalled = ""

# Linked clone (`true` for temporary usage)
linked_clone = false

# Make dynamic IP address to static IP, useful running server-like applications
make_dhcp_static = true

# Turn on/off nested virtulization
nested_virtulization = "off"

pvurl_prefix="https://gitee.com/get-set/myboxes/raw/master/provisioning"
######################
### End of Configurations

### Config Virtualbox and VMs.
######################
Vagrant.configure("2") do |config|

  # The following three config needs vagrant-hostmanager plugin installed: 'vagrant plugin install vagrant-hostmanager'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ip_resolver = proc do |vm, resolving_vm|
    if vm.id
      `VBoxManage guestproperty get #{vm.id} "/VirtualBox/GuestInfo/Net/1/V4/IP"`.split()[1]
    end
  end

  config.vm.box_check_update = false

  # common configurations
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = linked_clone
    vb.customize ["modifyvm", :id, "--groups", "/#{group}"]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "#{nested_virtulization}"]
    # pagefusion cannot be enabled on MacOS.
    vb.customize ["modifyvm", :id, "--pagefusion", "on"]
  end

  ### Configurations for each VM.
  vms.each do |m_name, m_config|
    config.vm.define "#{m_name}" do |m|

      # If centos node exists, intall vagrant-vbguest plugin to use synced folder (vagrant plugin install vagrant-vbguest)
      # m.vm.synced_folder "~/.Virtualboxes/.share/#{m_name}", "/srv", create: true, , SharedFoldersEnableSymlinksCreate: false

      m.vm.box = "#{m_config[0]}"
      m.vm.hostname = "#{m_name}"

      # The second nic, the first one is "Share" network
      # m.vm.network "private_network", ip: "#{m_config[3]}"
      m.vm.network "private_network", type: "dhcp"

      m.vm.provider "virtualbox" do |vb|
        vb.name = "#{m_name}"
        vb.memory = "#{m_config[2]}"
        vb.cpus = "#{m_config[1]}"
      end

      ### Provisionings that will be executed
      # Basic OS configurations: root password, mirrors, etc.
      m.vm.provision "file", source: "~/.ssh", destination: "/tmp/host.ssh"
      m.vm.provision "prepare os", type: "shell" do |s|
        s.path = "#{pvurl_prefix}/shell/bootstrap-os.sh"
        s.args = ["#{new_user}","#{packages_preinstalled}"]
      end

      if make_dhcp_static
        # The first NIC is set to DHCP by default, use the following script to set to STATIC, with IP address not changed.
        m.vm.provision "dhcp to static", type: "shell", path: "#{pvurl_prefix}/shell/dhcp2static.sh"
      end

    end
  end

end
