# -*- mode: ruby -*-
# vi: set ft=ruby :


### Configurations 
# [VM] name, cpus, memory(MB), ip(private), group name
# [OS] root-password, http(s)_proxy, packages to install
######################
group = "templates"
vms = {
  :centos => ['bento/centos-8', '1', '2048', '10.1.1.5'],
  :ubuntu => ['bento/ubuntu-18.04', '1', '2048', '10.1.1.6'],
}
# Packages you want to install during provisioning
packages_preinstalled = "vim git curl wget tree"
# Turn on/off nested virtulization
nested_virtulization = "off"


pvurl_prefix="https://gitee.com/get-set/myboxes/raw/master/provisioning"
######################
### End of Configurations

### Config Virtualbox and VMs.
######################
Vagrant.configure("2") do |config|

  # The following three config needs vagrant-hostmanager plugin installed: 'vagrant plugin install vagrant-hostmanager'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  config.vm.box_check_update = false

  # common configurations
  config.vm.provider "virtualbox" do |vb|
    vb.linked_clone = true
    vb.customize ["modifyvm", :id, "--groups", "/#{group}"]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "#{nested_virtulization}"]
    # pagefusion cannot be enabled on MacOS.
    # vb.customize ["modifyvm", :id, "--pagefusion", "on"]
  end

  ### Configurations for each VM.
  vms.each do |m_name, m_config|
    config.vm.define "#{m_name}" do |m|

      # If centos node exists, intall vagrant-vbguest plugin to use synced folder (vagrant plugin install vagrant-vbguest)
      # m.vm.synced_folder "~/.Virtualboxes/.share/#{m_name}", "/srv", create: true, , SharedFoldersEnableSymlinksCreate: false

      m.vm.box = "#{m_config[0]}"
      m.vm.hostname = "#{m_name}"
      m.vm.network "private_network", ip: "#{m_config[3]}"

      m.vm.provider "virtualbox" do |vb|
        vb.name = "#{m_name}"
        vb.memory = "#{m_config[2]}"
        vb.cpus = "#{m_config[1]}"
      end

      ### Provisionings that will be executed
      # Basic OS configurations: root password, mirrors, etc.
      m.vm.provision "file", source: "~/.ssh", destination: "/tmp/host.ssh"
      m.vm.provision "prepare os", type: "shell" do |s|
        s.path = "#{pvurl_prefix}/shell/bootstrap-os.sh"
        s.args = ["#{packages_preinstalled}"]
      end

    end
  end

end
